### ISSUE TITLE
Trying to compile HelloWorld with Xcode 7 "ld: library not found for -lmmwormhole"

### ISSUE THREAD

**Issue by poornerd** [Telerik-Verified-Plugins/AppleWatch#14]
I am trying to compile the Hello World example like in the readme, and am getting this error.

Does anyone else have this problem?
- Brian

```
ld: library not found for -lmmwormhole
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
    Ld build/emulator/HelloCordova\ WatchKit\ 1\ Extension.appex/HelloCordova\ WatchKit\ 1\ Extension normal i386
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/Users/bp/myTest/applewatchtest/platforms/ios/cordova/build-debug.xcconfig,-project,HelloCordova.xcodeproj,ARCHS=i386,-target,HelloCordova,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/bp/myTest/applewatchtest/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/bp/myTest/applewatchtest/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /Users/bp/myTest/applewatchtest/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /Users/bp/myTest/applewatchtest/platforms/ios/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```

**Comment by poornerd** [comment]
This must have been some problem related to a previous Xcode version (6.4) or a previous HelloWorld test. I just deleted and added the linked library in Xcode and it compiled (still can't get the HelloWorld running).

**Comment by sandman4sure** [comment]
I have the same problem
`ld: library not found for -lmmwormhole`
Cleaning the whole project doesn't work.
What else can I try?

**Comment by EddyVerbruggen** [comment]
@sandman4sure can you perhaps send me your xcode project? It could be many things and I'll gladly take a look. (eddyverbruggen at gmail)

**Comment by EddyVerbruggen** [comment]
For others: the problem for @sandman4sure was solved by deselecting and selecting those targets on the right for the libmmwormhole.a file:

<img width="950" alt="screen shot 2015-10-28 at 15 30 49" src="https://cloud.githubusercontent.com/assets/1426370/10792139/c2acd584-7d8b-11e5-8b06-016bac33589e.png">

**Comment by bhautikappv** [comment]
I have the same problem with older verison xcode(6.3) project.
I run code in xCode 8.0 and it's give me error like show in the following screen.

![screen](https://cloud.githubusercontent.com/assets/24278294/21119196/7d0e9baa-c08f-11e6-9877-49e2f5783c31.png)

Any one help me to sort out?

Please reply ASAP.

Thanks in Advance.

**Comment by karuppasamypandian0856** [comment]
This solved my problem.Please try this
http://stackoverflow.com/questions/31139534/pod-error-in-xcode-id-framework-not-found-pods
