### ISSUE TITLE
Roadmap Questions

### ISSUE THREAD

**Issue by bfischer1121** [Telerik-Verified-Plugins/AppleWatch#3]
Had a couple questions about the roadmap:
- Will this plugin/paradigm support creating native apps in watchOS 2 when it lands? Any foreseen problems?
- Are there any plans for a more generic interface to the native components' configurations? I'd like to be able to look up any kind of config in the native docs and be able to set it because the engine consuming these JSON objects is simply transforming them to native code.

Thanks for the excellent plugin.

**Comment by EddyVerbruggen** [comment]
Hi @bfischer1121 thanks for the questions.

We will do our best to make the current approach work with Watch OS2 as well.

We're trying to expose all possible properties to the JS API. Note that there is only so much you can do programmatically in Watch OS. The nitty gritty details must be tweaked in the Storyboard file. Fortunately there is a way to override the bundled storyboard with your own if you really have to. If you have any specific config in mind let me know and I'll see if it can be added to the current implementation.

**Comment by bfischer1121** [comment]
Thanks Eddy! Great answers!
