### ISSUE TITLE
WatchOS 2 integration 

### ISSUE THREAD

**Issue by omaxlive** [Telerik-Verified-Plugins/AppleWatch#30]
As I read in other questions this plugin already supports watchOS 2 but I'am not sure if it's for all cordova projects or only for Telerik platform.

message by @e2l3n 

> "The latest version 1.0.3 of the plugin supports WatchOS 2.0 and it is not compatible with WatchOS 1.0 generally because of Apple dropping support for WatchOS 1.0. Please, note that 1.0.3 currently adds support only in Telerik Platform. Support for regular Cordova projects will be added in future."

Can I use it for my cordova project? 

If yes, then going to "Xcode" File > New > Target > WatchOS > Application: Should I select "WatchKit App" or "WatchKit App for watchOS 1" ?

![captura de pantalla 2016-08-28 a las 13 18 05](https://cloud.githubusercontent.com/assets/3239132/18033333/e4502160-6d21-11e6-89d2-8a735de42f18.png)

Thank you!

**Comment by JoseWalker** [comment]
it seems nobody is really paying attention to this plugin from Telerik, or is not in their interests to help much here unless you have a paid subscription with them. Pity pity pity.

**Comment by EddyVerbruggen** [comment]
@JoseWalker This is the only plugin in this entire GitHub account that has a serious conflict in required scripts between the Cordova CLI and the Telerik's tools.

For version 1 we've gone to great lengths to make the `master` branch works great with the CLI and maintained a separate branch for Telerik's tools. Thát's how much we values the CLI compatibility. Trust me it's been very hard to get those scripts right, just look at them..

With WatchOS1's deprecation mess we had to do it all again but to be honest we've never had the adoption we hoped it would have in the Cordova community so we invested our time in other areas where we thought we would make a bigger impact on the community - while (of course) keeping our paying customers happy. If that's not fair I don't know what is.

It shouldn't be superhard to transform the already working WatchOS1 support to OS2, looking at what Telerik has done to upgrade the Telerik scripts to OS2. Anyone is **more than welcome** to chip in.

**Comment by JoseWalker** [comment]
That's all what I wanted! a reply!

You're right, I do appreciate a lot the effort you've put on this! as I said just wanted your attention by playing reverse psychology, which clearly works!

The message I wanted to convey is: lots of people are looking into this plugin, and like me, it seems they start to feel frustrated by spending hours and days into something you probably know right away! 

As I stated in other comments, WE ARE WILLING TO PAY!, to make this work for our project. If you by some meaning want to help us and earn some money! welcome on board, but my team is spending plenty of time that you probably can solve very easily!

As said! truly thanks for this plugin! and forgive my play to catch your attention.
