### ISSUE TITLE
Upload to the AppStore

### ISSUE THREAD

**Issue by omaxlive** [Telerik-Verified-Plugins/AppleWatch#34]
First of all, thanks for the plugin! After some days working with this plugin. (v0.6.0 Master). Now I need to release the app to the AppStore. xCode gave me next error when I try to upload.

> ERROR ITMS-90636: "Invalid WatchKit Support. Starting June 1, 2016, all new watchOS apps submitted to the App Store must be native apps built with the watchOS 2 SDK or later. iPhone apps that introduce a new WatchKit extension for watchOS 1.0 will no longer be accepted. Learn more about developing for watchOS: https://developer.apple.com/watchos/"

Any idea how to solve it? @EddyVerbruggen & @e2l3n

**Comment by EddyVerbruggen** [comment]
Hmm, that's a pity. So in that case most of your code is still OK but you need to change a few bits in Xcode to reflect what we've done in [this branch](https://github.com/Telerik-Verified-Plugins/AppleWatch/tree/appbuilder) to upgrade to WatchOS 2. There are a few specific bits in there for AppBuilder which you may need to do differently but that's not something I can assist with at the moment.

**Comment by JoseWalker** [comment]
As stated by EddyVerbruggen "_There are a few specific bits in there for AppBuilder which you may need to do differently but that's not something I can assist with at the moment._"

Eddy! you shouldn't release some piece of code and let the world to figure out how it works! that's not nice! later on you might have problem with another pice of code from somebody else and you will greatly appreciate some help! otherwise be nice and remove this plugin from Git!

**Comment by JoseWalker** [comment]
Hey Omar! would you share your findings with the rest of the world? write a blog post of how to overcome this plugin? how to integrate it with an existing Cordova app? please let me know, I might even pay you some fee to help us out with some code, if you work as a freelancer. Drop me an email to jwalker@river-ss.com

**Comment by JordiOrriols** [comment]
I had the exact same problem and had to desist because I had no Idea how to proceed, a little help as Jose says would be highly appreciated! Eddy The world needs you super powers! ;)

**Comment by JoseWalker** [comment]
Jordi, the same offer to you! share your knowledge with us, let us overcome this problem together and I can pay some fee... write me directly... anybody!

**Comment by omaxlive** [comment]
Hi @EddyVerbruggen Thanks for your answer. Can you please tell me what files should I look first? I don't know from where to start. I was trying installing that branch but it's normal to get error because it's for telerik. I guess we need to change just a bit for making it installable for Cordova projects, I also think for you would be super easy to make that change because you know how the plugin works or just tell me what should I try and help other people looking for the same solution.

Hi @JoseWalker @JordiOrriols 
I hope we can have some help and if I find a solution, I will share of course.

**Comment by EddyVerbruggen** [comment]
@JoseWalker Awesome comments mate.

This was released well over a year ago when WatchOS2 didn't exist yet and it worked great. See #30 for my invitation to help out.

I would like to do the upgrade, but there's a 100 other repo's that need my attention just as much as this one.

**Comment by JoseWalker** [comment]
@EddyVerbruggen can you cooperate with my company for couple hours or so?! we'll pay! for us is this or learn swift which is not an option for the moment having found this plugin.

**Comment by omaxlive** [comment]
I just installed the v1.0.3 correctly by commenting the telerik code and uncommenting the cordova one in "plugin.xml" but still getting the message "No WatchKit Extension found, please open your project in XCode, then do: File > New > Target > Apple Watch > WatchKit App" 

I will keep trying...

plugin.xml

```
 <!--     (1/2) THESE HOOKS ARE FOR TELERIK APPBUILDER AND ARE ENABLED IN THE appbuilder BRANCH OF THIS REPOSITORY 
        <hook type="before_plugin_install" src="src/ios/hooks/ab/prerequisites.js"/>
        <hook type="before_plugin_install" src="src/ios/hooks/ab/add-targets.js"/> -->


        <!-- (2/2) THESE HOOKS ARE FOR THE CORDOVA CLI -->
        <!-- execute these once -->
        <hook type="after_plugin_install" src="src/ios/hooks/cordova/copy_watchkitfiles.js" />
        <hook type="after_plugin_install" src="src/ios/hooks/cordova/fix_watchkitapp_buildtarget.js" />
        <!-- execute this one every time because the user may have done updates -->
        <hook type="after_prepare" src="src/ios/hooks/cordova/copy_custom_storyboard.js" />
```

Console result:

```
                                 Configuring the                                      
                             Cordova AppleWatch Plugin                                

                          `@@@@@@@@@@@@@@@@@@@@@@@@@@@@@:                             
                         @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@`                           
                        @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@:                          
                       @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                          
                      ;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                         
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                         
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@;                        
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#                        
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                        
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@@@                 
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@@@                 
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@@@                 
                      @@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@@@@@  @@@@@                 
                      @@@@@@@@@@@@@@@@@@@@   @@@@@@@@@@@@@@@@@  @@@@@                 
                      @@@@@@@@@@@@@@@@@@@#  @@@@@@@@@@@@@@@@@@  @@@@@                 
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@@@                 
                      @@@@@@@@@@@@@@@`   ,`    @@@@@@@@@@@@@@@                        
                      @@@@@@@@@@@@@@`          ,@@@@@@@@@@@@@@                        
                      @@@@@@@@@@@@@@          `@@@@@@@@@@@@@@@                        
                      @@@@@@@@@@@@@'          @@@@@@@@@@@@@@@@                        
                      @@@@@@@@@@@@@,          @@@@@@@@@@@@@@@@                        
                      @@@@@@@@@@@@@;          @@@@@@@@@@@@@@@@                        
                      @@@@@@@@@@@@@@           @@@@@@@@@@@@@@@  @@@                   
                      @@@@@@@@@@@@@@            @@@@@@@@@@@@@@  @@@                   
                      @@@@@@@@@@@@@@            @@@@@@@@@@@@@@  @@@                   
                      @@@@@@@@@@@@@@@          +@@@@@@@@@@@@@@  @@@                   
                      @@@@@@@@@@@@@@@:         @@@@@@@@@@@@@@@  @@@                   
                      @@@@@@@@@@@@@@@@.  +#   @@@@@@@@@@@@@@@@  @@@                   
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@                   
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@                   
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@                   
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@                   
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@                   
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@                   
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@                   
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                        
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#                        
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@;                        
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                         
                      ;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                         
                       @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                          
                        @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@:                          
                         @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@`                           
                          `@@@@@@@@@@@@@@@@@@@@@@@@@@@@@:                             

No WatchKit Extension found, please open your project in XCode, then do: File > New > Target > Apple Watch > WatchKit App
```

**Comment by omaxlive** [comment]
I don't know what to try more. :/
- I add apple watch target (not watchOS1).
- Make the change commented in the last comment.
- Install the plugin correctly but the plugin can't find the watch target for some reason. Message result: "No WatchKit Extension found, please open your project in XCode, then do: File > New > Target > Apple Watch > WatchKit App".
- If anyone have a minimum idea how to solve it, is very welcome.

**Comment by JoseWalker** [comment]
I think the ultimate solution will be, forget that this plugin exists, and start learning swift. Here in Colombia we have a saying that goes something like: "This is like having a mother, but dead" (_Es como tener la mamá, pero tenerla muerta_).

Is nice to know that somebody took the time to develop something (thanks @EddyVerbruggen), but is a dead end, no were to go... is by far more expensive (in money) spend days on this matter, than paying yourself a course to learn swift for WatchOS, or hire someone who knows how, than having resources put into figuring out how something works without any help at all.

BTW, nobody replied about my monetary offer... that's pity too.

Regards.

**Comment by omaxlive** [comment]
Yeah @JoseWalker 
I would do that, but I already spent time and finished developing the app. Then I found this problem and I need a solution because loose more time starting a new project isn't a solution for me.

And yes @EddyVerbruggen I could also pay as @JoseWalker proposed.

**Comment by JoseWalker** [comment]
@omaxlive hmmm, frustrating having developed the app already and knowing that you MIGHT have lost all the work you have put into this because of the final stitch! 

But that final stitch... due to @EddyVerbruggen silence, which apparently seems to be the only one behind this plugin, will be very difficult for you to wrap up.

Anyways! the offer is still open, I'm moving to find something else... but if you figure out (one day) how to solve this without throwing your company's resources (time and money), let me know...

Regards @omaxlive

**Comment by EddyVerbruggen** [comment]
@JoseWalker well played again with your reverse psychology bs. We're not in the same timezone and I have a dayjob so it's a bit weird to call me "silent" when my last comment was yesterday.

Like I mentioned before: $$ is not the issue, time is.

But if you guys are willing to send me an offer I can't refuse then by all means go ahead on my personal email address. You can find it on my github profile. And while you're there take note of the rediculous amount of OSS work I'm doing besides my dayjob. People like you make me regret that.
