### ISSUE TITLE
Visual Studio Tools for Apache Cordova

### ISSUE THREAD

**Issue by ghost** [Telerik-Verified-Plugins/AppleWatch#8]
Hello.

I'm trying to integrate your plugin into my VS/TAC-based application.
And the main problem is, that ios project is recreated on every build action.

I wonder, is there any way to automate(by using hook (after_platform_add or before_plugin_add) for example) the following action:
"XCode
File > New > Target > Apple Watch: Language ObjC, Select Glance and Notifications > Finish > Activate"

I will be very appreciated for any suggestions.

**Comment by EddyVerbruggen** [comment]
Hi,

That's among the things our [hooks in the AppBuilder branch](https://github.com/Telerik-Verified-Plugins/AppleWatch/blob/appbuilder/plugin.xml#L48-L49) do. Although your requirement is largely the same you'll probably need to tweak them for VS.
